### ISSUE TITLE
Theme-snippet doesn't track product views

### ISSUE THREAD

**Issue by JasperMeurs** [tensworth/Shopify-Facebook-Pixel#2]
At the moment the theme-snippet doesn't track individual product views. Any plans of adding this function, @tensworth? Otherwise I'll be happy to look into it.

**Comment by tensworth** [comment]
fbq('track', 'ViewContent'); will track product page views as well as any page views as an event. This is included in the theme pixel already.

**Comment by JasperMeurs** [comment]
That's not entirely true. I added this code to Product.liquid:
`fbq('track', 'ViewContent', {
  content_ids: ['shopify_{{ product.id }}_{{ product.variants.first.id }}'],
  content_type: 'product'
});`

**Comment by tensworth** [comment]
I misunderstood. That's a great idea to use the content id's to grab the product info. I added this to the main theme pixel with an if statement to only include that snippet on the product page. You can update the main pixel with the updated theme-snippet.liquid and remove it from the product.liquid to keep your code nice and DRY. 

Thanks!

**Comment by JasperMeurs** [comment]
Nice! Bare in mind that the 'shopify_' prefix is because my product catalogue uses this prefix. This can be different for other shops... ;)

**Comment by tensworth** [comment]
Thanks for pointing that out about the shopify_ prefix. I updated the
snippet to remove that.

What are you using the shopify_ prefix for? I manage some pretty large
catalogs and I was wondering if this may help.

On a side note, wouldn't it be more helpful to use product.title or
variant.title instead of the product.id ?

Thanks for the input!

**Comment by JasperMeurs** [comment]
I'm using the Facebook Product Feed app by Flexify and they are using that prefix. That's the only reason.

**Comment by remotetech** [comment]
Hi, your code looks great. Thank you!
If your Shopify theme uses an Ajax pop-up for AddToCart the pixel is not firing on that event. Everything else is working great except for fbq('track', 'AddToCart');  event.
Please let me know if you have any answer for getting this event to trigger on Ajax pop-up AddToCart?
Thanks for any advice...Regards, James
